# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/538f00ea-aede-44e1-9cd6-56781f4a93af";
      fsType = "btrfs";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/538f00ea-aede-44e1-9cd6-56781f4a93af";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/538f00ea-aede-44e1-9cd6-56781f4a93af";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/ED35-0B58";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # secondary drive – label "proxima"
  fileSystems."/mnt/proxima" =
    { device = "/dev/disk/by-uuid/CC1C08D11C08B90A";
      fsType = "ntfs3";
      options = [ "nofail" "defaults" "uid=1000" "gid=1000" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1d586868-355a-4521-af01-8e2238773a4d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
