[backdrop]
blur_intensity = 0.14999999664723873
tint_intensity = 0.0

[bar]
order = [ "Main", "Bottom" ]

    [bar.Bottom]
    auto_hide = true
    background_opacity = 0.4999999888241291
    center = [ "session", "group:g1", "group:g2" ]
    end = []
    margin_edge = 0
    margin_ends = 330
    padding = 0
    position = "right"
    radius = 19
    radius_bottom_right = 0
    radius_top_right = 0
    reserve_space = false
    start = []
    thickness = 60
    widget_spacing = 13

        [[bar.Bottom.capsule_group]]
        fill = "surface_variant"
        id = "g1"
        members = [ "ram", "cpu", "network_rx", "network_tx" ]
        opacity = 0.0
        padding = 0.0

        [[bar.Bottom.capsule_group]]
        fill = "surface_variant"
        id = "g2"
        members = [ "screen_recorder", "caffeine", "screenshot", "clipboard", "bluetooth", "wallpaper" ]
        opacity = 0.0
        padding = 0.0

    [bar.Main]
    background_opacity = 0.4999999888241291
    capsule = true
    capsule_fill = "on_primary"
    capsule_opacity = 0.24999999441206455
    capsule_padding = 10.0
    capsule_radius = 11
    center = [ "active_window" ]
    end = [ "tray", "battery", "notifications", "network", "clock", "control-center" ]
    margin_edge = 5
    margin_ends = 5
    padding = 0
    radius = 14
    scale = 1.0500000081956387
    start = [ "launcher", "spacer_1", "workspaces", "media" ]
    thickness = 40
    widget_spacing = 8

[control_center]
sidebar = "full"

[desktop_widgets]
schema_version = 1
widget_order = [
    "desktop-widget-0000000000000003",
    "desktop-widget-0000000000000004",
    "desktop-widget-0000000000000005",
    "desktop-widget-0000000000000006",
    "desktop-widget-0000000000000007"
]

    [desktop_widgets.grid]
    cell_size = 24
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    cx = 1.9384231567382812
    cy = 608.4830322265625
    output = "eDP-1"
    rotation = -1.5707963705062866
    scale = 6.1123208999633789
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        aspect_ratio = 1.9000000000000001
        background = false
        background_opacity = 0.0
        background_padding = 14.0
        background_radius = 0.0
        bands = 24.0
        centered = true
        high_color = "secondary"
        low_color = "primary"
        mirrored = true
        show_when_idle = false

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    cx = 1688.118408203125
    cy = 174.95263671875
    output = "eDP-1"
    rotation = 0.0
    scale = 1.763157844543457
    type = "weather"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        background = true
        background_opacity = 0.47000000000000003
        background_padding = 0.0
        background_radius = 17.0
        shadow = false

    [desktop_widgets.widget.desktop-widget-0000000000000005]
    cx = 296.16000366210938
    cy = 976.4000244140625
    enabled = false
    output = "eDP-1"
    rotation = 0.0
    scale = 1.6000000238418579
    type = "media_player"

        [desktop_widgets.widget.desktop-widget-0000000000000005.settings]
        background_opacity = 0.51000000000000001
        background_padding = 16.0
        background_radius = 16.0
        layout = "horizontal"
        shadow = false

    [desktop_widgets.widget.desktop-widget-0000000000000006]
    cx = 1530.5
    cy = 1021.0999755859375
    output = "eDP-1"
    rotation = 0.0
    scale = 1.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000006.settings]
        background = true
        background_opacity = 0.53000000000000003
        background_padding = 17.0
        background_radius = 17.0
        shadow = false
        show_label = true
        stat = "net_rx"
        stat2 = "net_tx"

    [desktop_widgets.widget.desktop-widget-0000000000000007]
    cx = 1734.029052734375
    cy = 1021.358642578125
    output = "eDP-1"
    rotation = 0.0
    scale = 0.9930838942527771
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000007.settings]
        background_opacity = 0.54000000000000004
        background_padding = 17.0
        background_radius = 17.0
        shadow = false
        show_label = true
        stat = "cpu_usage"
        stat2 = "cpu_temp"

[dock]
background_opacity = 0.40000000000000002
cross_axis_padding = 0
enabled = true
icon_size = 30
inactive_opacity = 0.4999999888241291
inactive_scale = 0.65000000968575478
item_spacing = 0
magnification = false
main_axis_padding = 9
margin_edge = 5
padding = 1
radius = 14
reserve_space = true
show_dots = true
show_instance_count = false

[hooks]
started = "noctalia msg action screen-lock & /home/rodein/NixDOTs/home/dotfiles/my-scripts/startapps.sh"

[idle]
behavior_order = [ "lock", "screen-off", "suspend" ]
pre_action_fade_seconds = 10

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 800

    [idle.behavior.suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 1200

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 1
widget_order = [
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003"
]

    [lockscreen_widgets.grid]
    cell_size = 64
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    cx = 964.0
    cy = 728.0
    output = "eDP-1"
    rotation = 0.0
    scale = 1.0
    type = "login_box"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    cx = 301.25
    cy = 1065.0999755859375
    output = "eDP-1"
    rotation = 0.0
    scale = 1.3366012573242188
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = true
        background_opacity = 0.54000000000000004
        background_padding = 6.0
        background_radius = 18.0
        shadow = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    cx = 1616.0
    cy = 1069.5
    output = "eDP-1"
    rotation = 0.0
    scale = 1.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background_opacity = 0.54000000000000004
        background_padding = 17.0
        background_radius = 17.0
        format = "{:%H:%M:%S}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    cx = 964.0
    cy = 525.07171630859375
    output = "eDP-1"
    rotation = 0.0
    scale = 1.2479023933410645
    type = "sticker"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background_opacity = 0.51000000000000001
        background_padding = 16.0
        background_radius = 16.0
        image_path = "/home/rodein/Pictures/Wallpapers/pfp.jpg"
        opacity = 1.0

[notification]
allowed_urgencies = [ "low", "normal", "critical" ]
background_opacity = 0.39999999105930328
layer = "overlay"
offset_x = 5
offset_y = 5
scale = 0.90000000596046448

[osd]
background_opacity = 0.9499999787658453
keyboard_layout = false
offset_x = 5
offset_y = 0
position = "bottom_left"

[shell]
font_family = "Inter"
lang = "en"
settings_show_advanced = true
telemetry_enabled = false
ui_scale = 0.85000000521540642

    [shell.panel]
    borders = false
    clipboard_placement = "floating"
    control_center_placement = "floating"
    launcher_placement = "floating"
    open_near_click_clipboard = true
    open_near_click_control_center = true
    open_near_click_launcher = true
    open_near_click_session = true
    open_near_click_wallpaper = true
    session_placement = "floating"
    transparency_mode = "glass"
    wallpaper_placement = "floating"

    [shell.screen_corners]
    enabled = true
    size = 25

    [shell.shadow]
    alpha = 0.99999997764825821
    direction = "down_right"

[system.monitor]
gpu_poll_seconds = 10

[theme]
community_palette = "m3-content"
custom_palette = "ADW"
source = "wallpaper"
wallpaper_scheme = "vibrant"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "ghostty", "niri" ]
    community_ids = [ "neovim", "discord", "steam", "yazi" ]

[wallpaper]
directory = "/home/rodein/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/rodein/Pictures/Wallpapers/wallhaven-9or96k.jpg"

    [wallpaper.last]
    path = "/home/rodein/Pictures/Wallpapers/wallhaven-9or96k.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/rodein/Pictures/Wallpapers/wallhaven-9or96k.jpg"

[weather]
auto_locate = true

[widget.active_window]
max_length = 700
title_scroll = "always"

[widget.audio_visualizer]
mirrored = false
show_when_idle = true
width = 300.0

[widget.clock]
format = "{:%H:%M}    {:%d.%m}"

[widget.control-center]
capsule = true
capsule_opacity = 0.0
capsule_padding = 10.0
scale = 1.2

[widget.cpu]
display = "text"
stat = "cpu_temp"

[widget.launcher]
capsule = true
capsule_opacity = 0.0
capsule_radius = "auto"
custom_image = "/home/rodein/.local/state/noctalia/logos/nix-snowflake-white.svg"
glyph = ""
scale = 1.2

[widget.media]
art_size = 36.0
capsule_padding = 4.0
capsule_radius = 10
hide_when_no_media = true
max_length = 400
min_length = 0
scale = 0.94999999999999996
title_scroll = "always"

[widget.network]
show_label = false

[widget.network_rx]
display = "text"
scale = 0.85000000000000009

[widget.network_tx]
display = "text"
scale = 0.85000000000000009

[widget.screen_recorder]
script = "scripts/screen_recorder.lua"
type = "scripted"

[widget.session]
font_weight = 700
scale = 1.55

[widget.spacer_1]
length = 10
type = "spacer"

[widget.spacer_2]
type = "spacer"

[widget.sysmon]
stat = "net_rx"

[widget.tray]
capsule = true
capsule_opacity = 0.0
capsule_radius = 10.0
drawer = true

[widget.workspaces]
display = "none"