# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f39b3375-7cdf-4798-9cf5-993942a35ec7";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/f39b3375-7cdf-4798-9cf5-993942a35ec7";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/f39b3375-7cdf-4798-9cf5-993942a35ec7";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EBF6-6FE9";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # seccond drive
  fileSystems."/mnt/origin" = 
    { device = "/dev/disk/by-uuid/d5d14b6e-5752-4362-a648-3019d5377c66";
      fsType = "btrfs"; 
      options = [ "nofail" "defaults" ]; 
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Remap right Ctrl to Shift on internal keyboard
  services.keyd = {
    enable = true;
    keyboards.internal = {
      ids = [ "0b05:19b6" ];
      settings = {
        main = {
          rightcontrol = "rightshift";
        };
      };
    };
  };
}
